BUILDS_DIR = "builds"

TASKS_YAML_FILENAME = "tasks.yaml"
BUILDS_YAML_FILENAME = "builds.yaml"

PATH_TO_TASKS = f"{BUILDS_DIR}/{TASKS_YAML_FILENAME}"
PATH_TO_BUILDS = f"{BUILDS_DIR}/{BUILDS_YAML_FILENAME}"
